[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oyto_mini = "Ack3dg9utXRbtMY9LDsNWuZRT7VUoKUwKrsgoyjSXirM"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
