[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oyto_mini = "AiD45wxFcNuh1QC1EAU5i3dxbyVGTyNnZUdiHPbh8Fvk"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/cXTcihI0uHbLOrY9DDgl4"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
